// The Grinches Attack Christmas — ROSTER DATA
// Separate from ONBC's roles.js. Descriptions are drawn from GAC_SPEC.md.
// Each entry: { id, name, image, team, desc }. Duplicate cards (Grinch ×3,
// Elf ×6) get a numbered id suffix so the grid keys stay unique.

export const GAC_ROSTER = [
  // ---- Waking roles (night order) ----
  { id: "Sam",        name: "Sam the Snowman",   image: "Roles_Active/Sam.jpg",        team: "moderator",
    desc: "The moderator. Awake all game, runs the night and tracks results. Holds no team and cannot win or lose." },
  { id: "Cupid",      name: "Cupid",             image: "Roles_Active/Cupid.jpg",      team: "christmas",
    desc: "Night 1: links two players as lovers. If one dies, so does the other. A cross-team couple left as the last two alive win together." },
  { id: "Calvin",     name: "Scott Calvin",      image: "Roles_Active/Calvin.jpg",     team: "christmas",
    desc: "Learns who was dealt Santa on night 1 (re-checks night 2 if Wet Bandits are in play). When Santa dies, he takes over Santa's nightly check." },
  { id: "Wet",        name: "Wet Bandits",       image: "Roles_Active/Wet.jpg",        team: "christmas",
    desc: "Night 1 only: steal the center card or another player's card and look. The stolen card becomes you; they get the center card." },
  { id: "Shelf",      name: "Elf on the Shelf",  image: "Roles_Active/Shelf.jpg",      team: "christmas",
    desc: "Each night, protect one player (not yourself) from death. Cannot protect the same player two nights in a row." },
  { id: "Grinch1",    name: "Grinch",            image: "Roles_Active/Grinch.jpg",     team: "grinch",
    desc: "Each night, the Grinches agree on one player to kill. Win when Grinches equal or outnumber everyone else." },
  { id: "Grinch2",    name: "Grinch",            image: "Roles_Active/Grinch.jpg",     team: "grinch",
    desc: "Each night, the Grinches agree on one player to kill. Win when Grinches equal or outnumber everyone else." },
  { id: "Grinch3",    name: "Grinch",            image: "Roles_Active/Grinch.jpg",     team: "grinch",
    desc: "Each night, the Grinches agree on one player to kill. Win when Grinches equal or outnumber everyone else." },
  { id: "BadSanta",   name: "Bad Santa",         image: "Roles_Active/BadSanta.jpg",   team: "grinch",
    desc: "A Grinch who must say the word \"Grinch\" out loud at least once each day, or be eliminated." },
  { id: "Krampus",    name: "Krampus",           image: "Roles_Active/Krampus.jpg",    team: "grinch",
    desc: "Once per game: turn the night's victim into a Grinch instead of letting them die. Wakes with the Grinches." },
  { id: "Mrs",        name: "Mrs. Claus",        image: "Roles_Active/Mrs.jpg",        team: "christmas",
    desc: "Shown the night's victim. Once per game each: save a player with a nice cookie, and poison a player with a bad one." },
  { id: "Santa",      name: "Santa Claus",       image: "Roles_Active/Santa.jpg",      team: "christmas",
    desc: "Each night, learn whether one player is on the Grinch team or the Christmas team (naughty or nice)." },
  { id: "Belsnickel", name: "Belsnickel",        image: "Roles_Active/Belsnickel.jpg", team: "christmas",
    desc: "Each night, kill one player you believe is attacking Christmas. You can be wrong." },
  { id: "Buddy",      name: "Buddy the Elf",     image: "Roles_Active/Buddy.jpg",      team: "christmas",
    desc: "Once per game: swap two players. Any fate aimed at one (like a kill) moves with the swap." },

  // ---- Non-waking roles ----
  { id: "Elf1", name: "Elf", image: "Roles_Active/Elf.jpg", team: "christmas", desc: "A regular elf with no special power. Help Christmas by voting out the Grinches." },
  { id: "Elf2", name: "Elf", image: "Roles_Active/Elf.jpg", team: "christmas", desc: "A regular elf with no special power. Help Christmas by voting out the Grinches." },
  { id: "Elf3", name: "Elf", image: "Roles_Active/Elf.jpg", team: "christmas", desc: "A regular elf with no special power. Help Christmas by voting out the Grinches." },
  { id: "Elf4", name: "Elf", image: "Roles_Active/Elf.jpg", team: "christmas", desc: "A regular elf with no special power. Help Christmas by voting out the Grinches." },
  { id: "Elf5", name: "Elf", image: "Roles_Active/Elf.jpg", team: "christmas", desc: "A regular elf with no special power. Help Christmas by voting out the Grinches." },
  { id: "Elf6", name: "Elf", image: "Roles_Active/Elf.jpg", team: "christmas", desc: "A regular elf with no special power. Help Christmas by voting out the Grinches." },
  { id: "Scrooge",    name: "Ebenezer Scrooge",  image: "Roles_Active/Scrooge.jpg",    team: "christmas",
    desc: "May only mumble or say \"BAH HUMBUG\" all game. Say anything else and you're eliminated." },
  { id: "Cindy",      name: "Cindy Lou Who",     image: "Roles_Active/Cindy.jpg",      team: "christmas",
    desc: "May secretly peek while the Grinches are awake to catch them — but if they notice, they'll likely kill you." },
  { id: "Frost",      name: "Jack Frost",        image: "Roles_Active/Frost.jpg",      team: "christmas",
    desc: "If you're killed, you take one player of your choice down with you (resolved at the start of the next day)." },
  { id: "Burger",     name: "Burgermeister Meisterburger", image: "Roles_Active/Burger.jpg", team: "christmas",
    desc: "On the Christmas team, but you only win if the Grinches win and steal Christmas." },
  { id: "CharlieBrown", name: "Charlie Brown",   image: "Roles_Active/CharlieBrown.jpg", team: "christmas",
    desc: "If the day's vote ends in an exact tie, you are the one who dies." },
  { id: "Yukon",      name: "Yukon Cornelius",   image: "Roles_Active/Yukon.jpg",      team: "christmas",
    desc: "You survive the very first attack made on you in the game. After that, you're as vulnerable as anyone." },
];
