// Print-reference data: team + one-sentence summary for each unique character.
// Teams: "christmas" (red), "grinch" (green), "neutral" (orange = third team).
// Summaries condensed from the official manual.

export const CHAR_REF = {
  "Hermey.jpg":   { team:"christmas", desc:"Looks at a center card (not the Krampus card) and becomes that role." },
  "Rudolph.jpg":  { team:"christmas", desc:"Looks at another player's card and takes on that role and team." },
  "Cupid.jpg":    { team:"christmas", desc:"Gives two players Mistletoe tokens; if one is accused, both leave town." },
  "Frosty.jpg":   { team:"christmas", desc:"Places the Magic Hat on a card, protecting it from being viewed or moved." },
  "Hinkle.jpg":   { team:"christmas", desc:"May take the Magic Hat token and place it on his own card." },
  "Hocus.jpg":    { team:"christmas", desc:"If the Magic Hat left the center, may move it to another player's card." },
  "Grinch.jpg":   { team:"grinch",    desc:"Wakes with the other Grinches to find out who they are." },
  "Krampus.jpg":  { team:"grinch",    desc:"Swaps the center Grinch card with another player's card without looking." },
  "BadSanta.jpg": { team:"grinch",    desc:"Wakes with the Grinches, then secretly looks at one other player's card." },
  "Scrooge.jpg":  { team:"grinch",    desc:"Grinch-team ally (not a Grinch) who sees who all the Grinches are." },
  "Zero.jpg":     { team:"neutral",   desc:"Tries to get Jack Skellington accused; only wins if Jack is accused. If Jack Skellington is not in the game, Zero only wins if Zero is accused." },
  "Misers.jpg":   { team:"christmas", desc:"Both Miser Brothers wake to look for each other." },
  "Max.jpg":      { team:"christmas", desc:"May tap the shoulder of the player to his left or right." },
  "Santa.jpg":    { team:"christmas", desc:"Looks at one player's card or two of the center cards." },
  "Calvin.jpg":   { team:"christmas", desc:"Looks at one of the center cards." },
  "Belsnickel.jpg":{ team:"christmas",desc:"Views up to two cards; if he sees a Grinch or Jack, he becomes it." },
  "Wet.jpg":      { team:"christmas", desc:"May swap his card with another player's, then view his new card." },
  "Mrs.jpg":      { team:"christmas", desc:"May view a center card, then must swap it with any player's card." },
  "Kevin.jpg":    { team:"christmas", desc:"May switch two other players' cards without looking at them." },
  "Buddy.jpg":    { team:"christmas", desc:"May shift everyone's card (but his own) one spot left or right." },
  "Future.jpg":   { team:"christmas", desc:"Sees everyone who looked at or moved any card or token tonight." },
  "Shelf.jpg":    { team:"christmas", desc:"Must swap his card with a center card without looking at it." },
  "Cindy.jpg":    { team:"christmas", desc:"Wakes and looks at her own card to see if it changed." },
  "Warlock.jpg":  { team:"grinch",    desc:"Grinch-team ally (not a Grinch) who sees and may view the Grinches' cards." },
  "Bernard.jpg":  { team:"christmas", desc:"Sees and may view the cards of Santa Claus and Scott Calvin." },
  "Present.jpg":  { team:"christmas", desc:"May flip a player's card face up; Grinches/Jack get flipped back down." },
  "Wise.jpg":     { team:"christmas", desc:"Places a random face-down Christmas Present token on any player's card." },
  "Yukon.jpg":    { team:"christmas", desc:"Views an unused Present token; if it's Gold, may view his own card." },
  "Elf.jpg":      { team:"christmas", desc:"No special ability, but definitely not a Grinch." },
  "Frost.jpg":    { team:"christmas", desc:"If accused, freezes the player he points at, stopping their theft." },
  "Skell.jpg":    { team:"neutral",   desc:"Only wins if he is accused of stealing Christmas. Never wakes." },
  "Burger.jpg":   { team:"grinch",    desc:"A Grinch who sticks out his thumb instead of waking with them." },
  "E.L.F.S..jpg": { team:"christmas", desc:"Protects the player he points to from any stealing accusation." },
  "Tiny.jpg":     { team:"christmas", desc:"Too full of hope to be accused; the next-most-voted is accused instead." },
  "Tiny2.jpg":    { team:"christmas", desc:"Too full of hope to be accused; the next-most-voted is accused instead." },
  "ASM.jpg":      { team:"christmas", desc:"Starts on the Christmas team; joins the Grinches if one votes for him." },
};

// Token descriptions for the print reference (condensed from the manual).
export const TOKEN_REF = [
  { file:"Heart of the Grinch.png",        desc:"You are now a Grinch.", cpt:true },
  { file:"Home of the Elves.png",          desc:"You are now an Elf, with no special abilities.", cpt:true },
  { file:"Pumpkin of Jack Skellington.png",desc:"You are now Jack Skellington; only win if accused.", cpt:true },
  { file:"Cane of Tiny Tim.png",           desc:"You are now Tiny Tim.", cpt:true },
  { file:"Snowflake of Jack Frost.png",    desc:"You are now Jack Frost.", cpt:true },
  { file:"Jetpack of the ELFS.png",        desc:"You are now in the E.L.F.S.", cpt:true },
  { file:"Working Christmas Day.png",      desc:"You may not speak, except to say 'Bah Humbug'.", cpt:true },
  { file:"Shame of the Naughty List.png",  desc:"Turn away from the others; you may speak but not look.", cpt:true },
  { file:"Voice of the Carolers.png",      desc:"You may not speak, only sing.", cpt:true },
  { file:"Weenie Whistle.png",             desc:"You may not speak, just whistle.", cpt:true },
  { file:"Gift of Nothingness.png",        desc:"No effect — as if you received nothing.", cpt:true },
  { file:"Gold.png",                       desc:"No effect (but matters for Yukon Cornelius).", cpt:true },
  { file:"Mistletoe.png",                  desc:"Cupid's token; the two holders fall in love and leave together if accused.", cpt:false },
  { file:"Magic Hat.png",                  desc:"The card it's on can't be viewed, moved, or given a Present token.", cpt:false },
];
